apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove-files
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning workspace..."
        rm -rf $(workspaces.source.path)/*
