apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove-files
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning workspace..."
        rm -rf $(workspaces.source.path)/*
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: python:3.11
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        echo "Running unit tests with nose..."
        pip install --upgrade pip
        pip install nose
        nosetests -v
